# Category.create!([
#   {name: "Space Exploration", hashtag: "#SpaceExploration"},
#   {name: "Artificial Intelligence", hashtag: "#ArtificialIntelligence"},
#   {name: "Tesla", hashtag: "#Tesla"}
# ])
# Tweet.create!([
#   {name: "VISIT FLORIDA", user: "VISITFLORIDA", text: "For #TravelTuesday, experience the past, present and future of space exploration at the Kennedy Space Center Visitor Complex. @ExploreSpaceKSC. #LoveFL https://t.co/DJLfcoWxAQ", category_id: 1, favorite_count: 46, retweet_count: 24, media?: true, profile_image_url: "http://pbs.twimg.com/profile_images/847178500285087744/pH8RfPjw_normal.jpg", tweet_url: "https://twitter.com/VISITFLORIDA/status/978644120179789824", date_posted: "2018-03-27", verified: true, isActive: true},
#   {name: "SPACE.com", user: "SPACEdotcom", text: "'Mars Ain't Gonna Be Easy': What Apollo 17 Leaders Are Saying About Future Space Exploration https://t.co/6u0mHTcK4K https://t.co/c0oYiMOKV6", category_id: 1, favorite_count: 49, retweet_count: 24, media?: true, profile_image_url: "http://pbs.twimg.com/profile_images/702230733683871744/m1BIofCt_normal.png", tweet_url: "https://twitter.com/SPACEdotcom/status/978671752879357952", date_posted: "2018-03-27", verified: true, isActive: true},
#   {name: "TwistedDoodles", user: "twisteddoodles", text: "Space exploration #science https://t.co/lHlXxOSZAW", category_id: 1, favorite_count: 2371, retweet_count: 852, media?: true, profile_image_url: "http://pbs.twimg.com/profile_images/2923852396/20613163743438c5ee92899367284184_normal.jpeg", tweet_url: "https://twitter.com/twisteddoodles/status/975645868765466624", date_posted: "2018-03-19", verified: true, isActive: true},
#   {name: "NASA", user: "NASA", text: "What makes a good researcher? @NASA_Langley looks at researchers developing concepts, technologies and improvements in aviation, studying the Earth’s atmosphere, and space exploration. Watch &amp; follow \"Life at the Lab\" at https://t.co/QyzPl8ArTO https://t.co/rBgeoJ2OTU", category_id: 1, favorite_count: 1019, retweet_count: 248, media?: true, profile_image_url: "http://pbs.twimg.com/profile_images/188302352/nasalogo_twitter_normal.jpg", tweet_url: "https://twitter.com/NASA/status/976597718872346625", date_posted: "2018-03-21", verified: true, isActive: true},
#   {name: "Jan Wörner", user: "janwoerner", text: "It is a pleasure to moderate today’s  #GNF panel „International Space Exploration - Report on ISEF-2 and Beyond“ @iafastro #IAFSpringMeetings in #Paris (T) https://t.co/rUTbVCPDSU", category_id: 1, favorite_count: 20, retweet_count: 4, media?: true, profile_image_url: "http://pbs.twimg.com/profile_images/821046250560782339/FLdmPTkk_normal.jpg", tweet_url: "https://twitter.com/janwoerner/status/979035546805825541", date_posted: "2018-03-28", verified: true, isActive: true},
#   {name: "Power BI", user: "MSPowerBI", text: "There's still time! Enter a space-themed Power BI report for a chance to win swag. See official rules for details. https://t.co/ayJ4SbOFwN https://t.co/99wOtfUVE3", category_id: 1, favorite_count: 3, retweet_count: 5, media?: true, profile_image_url: "http://pbs.twimg.com/profile_images/821834838659346432/m1mSM9Qf_normal.jpg", tweet_url: "https://twitter.com/MSPowerBI/status/979099561951158272", date_posted: "2018-03-28", verified: true, isActive: true},
#   {name: "NASA Ames", user: "NASAAmes", text: "Still searching for your dream job? Meet some of the inspiring @WomenNASA, whose #STEM careers have advanced space exploration: https://t.co/PKX52xz0NH https://t.co/fPNQDZTyLO", category_id: 1, favorite_count: 289, retweet_count: 78, media?: true, profile_image_url: "http://pbs.twimg.com/profile_images/639225022339375105/nxkm_C2E_normal.jpg", tweet_url: "https://twitter.com/NASAAmes/status/976258467437543424", date_posted: "2018-03-21", verified: true, isActive: true},
#   {name: "NASA_SLS", user: "NASA_SLS", text: "“This is a mission that truly will do what hasn’t been done and learn what isn’t known.\"\n\nDuring Exploration Mission-1, #NASASLS will send @NASA_Orion farther into deep space than any spacecraft built for humans has ever flown! MORE &gt;&gt; https://t.co/ZK3XHYSU0i https://t.co/jEqoMph3zX", category_id: 1, favorite_count: 229, retweet_count: 85, media?: true, profile_image_url: "http://pbs.twimg.com/profile_images/892863328489422848/oF2AqVXL_normal.jpg", tweet_url: "https://twitter.com/NASA_SLS/status/976601857987694595", date_posted: "2018-03-21", verified: true, isActive: true},
#   {name: "NASA_SLS", user: "NASA_SLS", text: "As @NASA sets its sights on returning to the #Moon, and preparing for #Mars, the agency is developing new opportunities in lunar orbit to provide the foundation for human exploration deeper into the solar system. READ MORE &gt;&gt; https://t.co/DgrT2rr77F", category_id: 1, favorite_count: 98, retweet_count: 38, media?: false, profile_image_url: "http://pbs.twimg.com/profile_images/892863328489422848/oF2AqVXL_normal.jpg", tweet_url: "https://twitter.com/NASA_SLS/status/978323195680972800", date_posted: "2018-03-26", verified: true, isActive: true},
#   {name: "NASA_SLS", user: "NASA_SLS", text: ".@NASA's Exploration Mission-1 is the first in a series of increasingly complex missions that will enable human deep-space exploration to the Moon and beyond. Learn more about the mission! &gt;&gt; https://t.co/9JGK6s1FEg https://t.co/a2Zqatt025", category_id: 1, favorite_count: 165, retweet_count: 49, media?: true, profile_image_url: "http://pbs.twimg.com/profile_images/892863328489422848/oF2AqVXL_normal.jpg", tweet_url: "https://twitter.com/NASA_SLS/status/977998558350790656", date_posted: "2018-03-25", verified: true, isActive: true},
#   {name: "NASA History Office", user: "NASAhistory", text: "Soviet Premier Nikita Khrushchev responded to President John F. Kennedy's March 7th letter suggesting teamwork in space exploration #OTD in 1962. In the letter Khrushchev responded positively to the idea of international cooperation. For more: https://t.co/qQAR6WljgE https://t.co/QQk6HiAdUS", category_id: 1, favorite_count: 127, retweet_count: 54, media?: true, profile_image_url: "http://pbs.twimg.com/profile_images/695361954018275330/RLTuGTD__normal.jpg", tweet_url: "https://twitter.com/NASAhistory/status/976126225981886464", date_posted: "2018-03-20", verified: true, isActive: true},
#   {name: "NASA Goddard", user: "NASAGoddard", text: "Investing in space exploration cannot be a success without collaboration. During the Goddard Symposium last week, NASA welcomed the many attendees who share in that dream. \nhttps://t.co/M2Qv3HgA8V https://t.co/bctxDW8AVS", category_id: 1, favorite_count: 60, retweet_count: 16, media?: true, profile_image_url: "http://pbs.twimg.com/profile_images/900017986215436289/yjd89SG3_normal.jpg", tweet_url: "https://twitter.com/NASAGoddard/status/977605982317662209", date_posted: "2018-03-24", verified: true, isActive: true},
#   {name: "Department for International Trade", user: "tradegovuk", text: "In future we will be launching space ships from the 🇬🇧 and will be able to find out what Mercury is made of. \n\n🚀 Space scientist @SuzieImberSpace tells 6-year-old Rumaysa how the UK is leading on space exploration ahead of the GREAT Festival of Innovation. #GREATInnovation https://t.co/qXxEnLT1mw", category_id: 1, favorite_count: 65, retweet_count: 32, media?: true, profile_image_url: "http://pbs.twimg.com/profile_images/929987679701389312/Pk9RsQfU_normal.jpg", tweet_url: "https://twitter.com/tradegovuk/status/976052394713862144", date_posted: "2018-03-20", verified: true, isActive: true},
#   {name: "Adler Planetarium", user: "AdlerPlanet", text: "The Adler Planetarium would like to wish a happy 90th birthday to Captain James A. Lovell, Jr.! Your dedication to science education and space exploration always inspires us to share the wonders of the Universe with Chicago and beyond. https://t.co/HshzL91COX", category_id: 1, favorite_count: 97, retweet_count: 28, media?: true, profile_image_url: "http://pbs.twimg.com/profile_images/790408632592637952/yDC0XymR_normal.jpg", tweet_url: "https://twitter.com/AdlerPlanet/status/977909245063651328", date_posted: "2018-03-25", verified: true, isActive: true},
#   {name: "The Hindu", user: "the_hindu", text: "They are on cloud nine. And justifiably so. They have earned a visit to National Aeronautics and Space Administration (NASA), the prestigious space exploration agency in USA . https://t.co/Uyt29PHmwT", category_id: 1, favorite_count: 135, retweet_count: 37, media?: false, profile_image_url: "http://pbs.twimg.com/profile_images/627376030282416128/pYl_LmcW_normal.jpg", tweet_url: "https://twitter.com/the_hindu/status/978962411695820800", date_posted: "2018-03-28", verified: true, isActive: true},
#   {name: "Emmanuel Macron", user: "EmmanuelMacron", text: "Great progress on artificial intelligence is happening in France. \nSamsung chooses France to locate its new research center on artificial intelligence, creating more than 100 jobs. \nThank you Young Sohn for taking the leap. #ChooseFrance #AIforhumanity https://t.co/Ud6jNZOw30", category_id: 2, favorite_count: 1425, retweet_count: 435, media?: true, profile_image_url: "http://pbs.twimg.com/profile_images/834424630630817795/TfyS4uXb_normal.jpg", tweet_url: "https://twitter.com/EmmanuelMacron/status/979069585398919169", date_posted: "2018-03-28", verified: true, isActive: false},
#   {name: "SUHEL SETH", user: "suhelseth", text: "Which Indian political parties would benefit the most from Artificial Intelligence? 😂😂😂", category_id: 2, favorite_count: 1406, retweet_count: 261, media?: false, profile_image_url: "http://pbs.twimg.com/profile_images/3271633610/3dce6613c7ec66f27662f822950f3590_normal.jpeg", tweet_url: "https://twitter.com/suhelseth/status/978888433690140672", date_posted: "2018-03-28", verified: true, isActive: false},
#   {name: "MIT Tech Review", user: "techreview", text: "Here's the Chinese government massively ambitious plan to lead in the field of artificial intelligence by 2030. #EmTechDigital https://t.co/sGVvBNRIoO", category_id: 2, favorite_count: 120, retweet_count: 97, media?: false, profile_image_url: "http://pbs.twimg.com/profile_images/875400785294532608/feOza3es_normal.jpg", tweet_url: "https://twitter.com/techreview/status/978536376206548992", date_posted: "2018-03-27", verified: true, isActive: false},
#   {name: "The Economist", user: "TheEconomist", text: "With artificial intelligence set to revolutionise business, the workplace could become fairer—or more oppressive. Our cover this week https://t.co/6SdT0W0kNy", category_id: 2, favorite_count: 161, retweet_count: 116, media?: true, profile_image_url: "http://pbs.twimg.com/profile_images/879361767914262528/HdRauDM-_normal.jpg", tweet_url: "https://twitter.com/TheEconomist/status/978934490096685056", date_posted: "2018-03-28", verified: true, isActive: false},
#   {name: "World Economic Forum", user: "wef", text: "Could artificial intelligence soon become #conscious? https://t.co/fgMaignX1z #AI https://t.co/SFrdNmBb1U", category_id: 2, favorite_count: 76, retweet_count: 84, media?: true, profile_image_url: "http://pbs.twimg.com/profile_images/565498192171507712/r2Hb2gvX_normal.png", tweet_url: "https://twitter.com/wef/status/978798854891102209", date_posted: "2018-03-28", verified: true, isActive: false},
#   {name: "MIT Tech Review", user: "techreview", text: "Artificial intelligence looks certain to revolutionize medicine, but research from Google Cloud suggests it may be more challenging than many people suspect. #EmTechDigital https://t.co/DOeoBn1p4j", category_id: 2, favorite_count: 109, retweet_count: 101, media?: false, profile_image_url: "http://pbs.twimg.com/profile_images/875400785294532608/feOza3es_normal.jpg", tweet_url: "https://twitter.com/techreview/status/978876104713830405", date_posted: "2018-03-28", verified: true, isActive: false},
#   {name: "nature", user: "nature", text: "Atomic force microscopy is revealing molecular structures with startling clarity. Artificial intelligence and automation could expand its potential https://t.co/787Z4N4dUi", category_id: 2, favorite_count: 125, retweet_count: 73, media?: false, profile_image_url: "http://pbs.twimg.com/profile_images/968803989339897856/s6iSl6t9_normal.jpg", tweet_url: "https://twitter.com/nature/status/978687358865432576", date_posted: "2018-03-27", verified: true, isActive: false},
#   {name: "World Economic Forum", user: "wef", text: "#AI will only learn what we teach it. This is a problem for #gender equality https://t.co/7PJCvBMOua https://t.co/BupZcxLCah", category_id: 2, favorite_count: 70, retweet_count: 70, media?: true, profile_image_url: "http://pbs.twimg.com/profile_images/565498192171507712/r2Hb2gvX_normal.png", tweet_url: "https://twitter.com/wef/status/978600532955758592", date_posted: "2018-03-27", verified: true, isActive: false},
#   {name: "Harvard Biz Review", user: "HarvardBiz", text: "Non-tech businesses are beginning to use artificial intelligence at scale https://t.co/yBvxw2B6ud via @TheEconomist", category_id: 2, favorite_count: 41, retweet_count: 43, media?: false, profile_image_url: "http://pbs.twimg.com/profile_images/890310669739991040/wXqj8htb_normal.jpg", tweet_url: "https://twitter.com/HarvardBiz/status/979047753979453440", date_posted: "2018-03-28", verified: true, isActive: false},
#   {name: "Parkinson's UK", user: "ParkinsonsUK", text: "We are tremendously excited to announce that we will be working with @benevolent_ai after winning the #BAIAward17 along with @CureParkinsonsT. Using Artificial Intelligence could help us achieve the first major breakthrough in treatment for 50 years. https://t.co/8KAXk9dfgS https://t.co/qW0gUKBeD7", category_id: 2, favorite_count: 81, retweet_count: 40, media?: true, profile_image_url: "http://pbs.twimg.com/profile_images/852088474291359745/eTqok5b8_normal.jpg", tweet_url: "https://twitter.com/ParkinsonsUK/status/978929437289910272", date_posted: "2018-03-28", verified: true, isActive: false},
#   {name: "MIT Tech Review", user: "techreview", text: "Artificial intelligence and automation are not likely to cause vast unemployment, but that doesn’t mean we shouldn’t be concerned about the impact on jobs. #EmTechDigital https://t.co/G3n70YSk0j", category_id: 2, favorite_count: 48, retweet_count: 41, media?: false, profile_image_url: "http://pbs.twimg.com/profile_images/875400785294532608/feOza3es_normal.jpg", tweet_url: "https://twitter.com/techreview/status/979019542000259072", date_posted: "2018-03-28", verified: true, isActive: false},
#   {name: "Steven Pinker", user: "sapinker", text: "I especially recommend AI expert Peter Bentley's \"The Three Laws of Artificial Intelligence: Dispelling Common Myths\" (I make similar arguments in Enlightenment Now). \nhttps://t.co/CmG6ypzu3b", category_id: 2, favorite_count: 168, retweet_count: 44, media?: false, profile_image_url: "http://pbs.twimg.com/profile_images/953839152511909888/-3EQDjTM_normal.jpg", tweet_url: "https://twitter.com/sapinker/status/979018753374638082", date_posted: "2018-03-28", verified: true, isActive: false},
#   {name: "Entrepreneur", user: "Entrepreneur", text: "Artificial intelligence will empower marketers, not replace them. https://t.co/2VB7fTsE7N", category_id: 2, favorite_count: 56, retweet_count: 36, media?: false, profile_image_url: "http://pbs.twimg.com/profile_images/474753665970868224/GcoCzmcI_normal.jpeg", tweet_url: "https://twitter.com/Entrepreneur/status/978785005869633536", date_posted: "2018-03-28", verified: true, isActive: false},
#   {name: "Tommy Campbell", user: "MrTommyCampbell", text: "Going from Barack Obama to Donald Trump is like going from cruising a Tesla down the coast to smashing a Go-Kart into a pile of burning diapers.", category_id: 3, favorite_count: 1799, retweet_count: 383, media?: false, profile_image_url: "http://pbs.twimg.com/profile_images/723660076368596992/fmNK3u_l_normal.jpg", tweet_url: "https://twitter.com/MrTommyCampbell/status/979045074154614784", date_posted: "2018-03-28", verified: true, isActive: false},
#   {name: "Lisa Abramowicz", user: "lisaabramowicz1", text: "Tesla bonds...ouch. The current implied yield of nearly 7.7% on Tesla 2025 debt is unsustainably high for the company, which needs to raise several billion dollars by the beginning of next year to remain viable: Bloomberg Intelligence's @JoelLevington1 https://t.co/MDFq6nhbOI", category_id: 3, favorite_count: 384, retweet_count: 293, media?: true, profile_image_url: "http://pbs.twimg.com/profile_images/953988799683416064/fW2Lcf5z_normal.jpg", tweet_url: "https://twitter.com/lisaabramowicz1/status/979006302834888704", date_posted: "2018-03-28", verified: true, isActive: false},
#   {name: "Tesla", user: "Tesla", text: "Model 3 is Popular Mechanics’ Car of the Year https://t.co/k0a9c4X6Wq", category_id: 3, favorite_count: 2280, retweet_count: 490, media?: false, profile_image_url: "http://pbs.twimg.com/profile_images/489192650474414080/4RxZxsud_normal.png", tweet_url: "https://twitter.com/Tesla/status/979115818557390848", date_posted: "2018-03-28", verified: true, isActive: false},
#   {name: "NPR", user: "NPR", text: "Facebook Down $80 Billion In Market Value, Playboy, SpaceX, Tesla Hit Delete https://t.co/b6NDb0Pk8H", category_id: 3, favorite_count: 332, retweet_count: 154, media?: false, profile_image_url: "http://pbs.twimg.com/profile_images/722199003845304320/s2zwEoao_normal.jpg", tweet_url: "https://twitter.com/NPR/status/979071075748257794", date_posted: "2018-03-28", verified: true, isActive: false},
#   {name: "Tesla", user: "Tesla", text: "Cool https://t.co/fOblj7xFLH", category_id: 3, favorite_count: 2526, retweet_count: 426, media?: false, profile_image_url: "http://pbs.twimg.com/profile_images/489192650474414080/4RxZxsud_normal.png", tweet_url: "https://twitter.com/Tesla/status/979131817662889984", date_posted: "2018-03-28", verified: true, isActive: false},
#   {name: "NVIDIA", user: "nvidia", text: "Announcing DGX-2, the world's most powerful AI system for the most complex AI challenges. DGX-2, the first 2 petaFLOP #deeplearning system, delivers 10X performance gain, driven by the new Tesla V100 32GB GPU and NVSwitch. https://t.co/slhJnisY6e #GTC18 https://t.co/Xi4W1ObfDp", category_id: 3, favorite_count: 308, retweet_count: 156, media?: true, profile_image_url: "http://pbs.twimg.com/profile_images/467079983936970752/LUOWehvo_normal.jpeg", tweet_url: "https://twitter.com/nvidia/status/978683273655169024", date_posted: "2018-03-27", verified: true, isActive: false},
#   {name: "The Wall Street Journal", user: "WSJ", text: "Tesla’s stock plunged more than 8% in Tuesday trading in the wake of a deadly accident involving a Tesla with an automated control system https://t.co/fNWUbdqv1O", category_id: 3, favorite_count: 98, retweet_count: 88, media?: false, profile_image_url: "http://pbs.twimg.com/profile_images/971415515754266624/zCX0q9d5_normal.jpg", tweet_url: "https://twitter.com/WSJ/status/978806399768645632", date_posted: "2018-03-28", verified: true, isActive: false},
#   {name: "Sheila Gunn Reid 🐀", user: "SheilaGunnReid", text: "Tesla is worth twice as much as Ford [estimate of the enterprise value of both companies], yet Ford made 6 million cars last year at a $7.6 billion profit while Tesla made 100,000 cars at a $2 billion loss, https://t.co/mq9XfsoKN9", category_id: 3, favorite_count: 192, retweet_count: 151, media?: false, profile_image_url: "http://pbs.twimg.com/profile_images/977749584595202048/SMpLpxug_normal.jpg", tweet_url: "https://twitter.com/SheilaGunnReid/status/978778222761459713", date_posted: "2018-03-27", verified: true, isActive: false},
#   {name: "The Wall Street Journal", user: "WSJ", text: "Tesla will soon need money again. The trouble is, raising it suddenly looks a lot more challenging. https://t.co/9EDdv1ZxdN", category_id: 3, favorite_count: 134, retweet_count: 94, media?: false, profile_image_url: "http://pbs.twimg.com/profile_images/971415515754266624/zCX0q9d5_normal.jpg", tweet_url: "https://twitter.com/WSJ/status/978957393886371840", date_posted: "2018-03-28", verified: true, isActive: false},
#   {name: "MarketWatch", user: "MarketWatch", text: "Tesla is just months away from a total collapse, a hedge-fund manager says https://t.co/HpfsAbks1c", category_id: 3, favorite_count: 111, retweet_count: 93, media?: false, profile_image_url: "http://pbs.twimg.com/profile_images/705601245596090368/Z6xUOnRg_normal.jpg", tweet_url: "https://twitter.com/MarketWatch/status/978661896747388930", date_posted: "2018-03-27", verified: true, isActive: false},
#   {name: "Inc.", user: "Inc", text: "In a bold move, Elon Musk deleted the Tesla and SpaceX Facebook pages--and it's amazing https://t.co/kHiyQBgHcf", category_id: 3, favorite_count: 67, retweet_count: 46, media?: false, profile_image_url: "http://pbs.twimg.com/profile_images/794517026672967680/M4bp9e6f_normal.jpg", tweet_url: "https://twitter.com/Inc/status/978695172681818112", date_posted: "2018-03-27", verified: true, isActive: false},
#   {name: "Ashlee Vance", user: "valleyhack", text: "The new Bernstein report on Tesla's manufacturing is rough https://t.co/hUfmAMB3Ur", category_id: 3, favorite_count: 151, retweet_count: 95, media?: true, profile_image_url: "http://pbs.twimg.com/profile_images/961884276118687745/VKtrw39y_normal.jpg", tweet_url: "https://twitter.com/valleyhack/status/979101143665057792", date_posted: "2018-03-28", verified: true, isActive: false},
#   {name: "NowThis", user: "nowthisnews", text: "Tesla might be on the verge of bankruptcy https://t.co/8HhylThiMp", category_id: 3, favorite_count: 124, retweet_count: 81, media?: true, profile_image_url: "http://pbs.twimg.com/profile_images/971789860548866049/LCponVal_normal.jpg", tweet_url: "https://twitter.com/nowthisnews/status/979018526441779200", date_posted: "2018-03-28", verified: true, isActive: false},
#   {name: "Lisa Abramowicz", user: "lisaabramowicz1", text: "Prices on $1.8 billion of Tesla bonds maturing in 2025 are falling to a new record low. https://t.co/wUfOjIXpj6", category_id: 3, favorite_count: 144, retweet_count: 95, media?: true, profile_image_url: "http://pbs.twimg.com/profile_images/953988799683416064/fW2Lcf5z_normal.jpg", tweet_url: "https://twitter.com/lisaabramowicz1/status/978684531506139136", date_posted: "2018-03-27", verified: true, isActive: false},
#   {name: "NTSB_Newsroom", user: "NTSB_Newsroom", text: "2 NTSB investigators conducting Field Investigation for fatal March 23, 2018, crash of a Tesla near Mountain View, CA.  Unclear if automated control system was active at time of crash. Issues examined include: post-crash fire, steps to make vehicle safe for removal from scene.", category_id: 3, favorite_count: 56, retweet_count: 74, media?: false, profile_image_url: "http://pbs.twimg.com/profile_images/848968894782074881/iMLaM01e_normal.jpg", tweet_url: "https://twitter.com/NTSB_Newsroom/status/978651644417265664", date_posted: "2018-03-27", verified: true, isActive: false}
# ])

Tweet.delete_all
Category.delete_all

# Instantiate Twitter gem object using figaro
client = Twitter::REST::Client.new do |config|
  config.consumer_key        = Figaro.env.consumer_key
  config.consumer_secret     = Figaro.env.consumer_secret
  config.access_token        = Figaro.env.access_token
  config.access_token_secret = Figaro.env.access_token_secret
end

# Create Categories
Category.create(
    name: "Space Exploration",
    hashtag: "#SpaceExploration",
    isActive: true
  )

Category.create(
    name: "Artificial Intelligence",
    hashtag: "#ArtificialIntelligence",
    isActive: false
  )

Category.create(
    name: "Tesla",
    hashtag: "#Tesla",
    isActive: false
  )


Category.all.each do |category|
    client.search("#{category.name} -rt", options = {lang: "en", tweet_mode: "extended", result_type: "popular" }).first(30).each do |tweet|
        tweet1 = Tweet.new(
            name: tweet.user.name,
            user: tweet.user.screen_name,
            text: tweet.attrs[:full_text],
            date_posted: tweet.created_at,
            category_id: category.id,
            favorite_count: tweet.favorite_count,
            retweet_count: tweet.retweet_count,
            media?: tweet.media?,
            verified: tweet.user.attrs[:verified],
            tweet_url: tweet.uri,
            profile_image_url: tweet.user.profile_image_uri,
            isActive: false
        )

        if tweet1.save == false
          p tweet1.errors
        end
    end
end

Category.first.tweets.each do |tweet|
  tweet.update(isActive: true)
end